### ISSUE TITLE
Steckbrief erstellen für Präsentation

### ISSUE THREAD

**Issue by Thom-Mon** [fh-erfurt/Businesshotel-Roommanager#1]
Everyone creates his own Profile Data.
With the following content:
    Name
    Alter
    Erfahrung (java oder informatik)
    Gamertag
    Systemspezifikationen des HauptPC (ist mehr als Gag gedacht aber wäre cool wenn mans hat)

**Comment by Thom-Mon** [comment]
Mein Steckbrief steht nun. Stelle ihn hier aber nicht direkt so rein. Werde ihn eher dann an Martin schicken, dass er schön in die Präsentation kommt.

Inhalt: | Name, Alter, Erfahrung, Gamertag, Systemspezifikationen
------------ | -------------

**Comment by nikschen** [comment]
Hab ebenso meinen Steckbrief fix gemacht und direkt zugestellt
