### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by nikschen** [fh-erfurt/Businesshotel-Roommanager#17]
-Room muss abstract werden
-category in Room sollte wegfallen, dafür category in hotelroom und conferenceroom jeweils als enum einführen, dabei vorerst die Kategorien aus der projektbeschreibung implementieren
-wie besprochen, den spezifischen räumen mehr inhalt geben, z.B. auststattungsmerkmale wie Highspeed Internet, Satelliten TV, Teeküche, Kaffeekapselautomat und bei conferenceRoom entsprechend anzahl beamer, leinwand vorhanden, Laptop/PC vorhanden, Fernseher vorhanden, anzahl whiteboards ...
-wie in der Gruppe besprochen,: sinnvolle Tests für Employee.createRoom(), Employee.deleteRoom() und Employee.changeRoomDetails() erstellen, am besten in einer RoomTestClass

**Comment by Thom-Mon** [comment]
#marius = Room abstract, category in Unterräume
#Thomas = mehr Inhalt für die Räume, und alle Tesfälle zu Rooms
