### ISSUE TITLE
Räume brauchen genaueren Plan für Belegung

### ISSUE THREAD

**Issue by nikschen** [fh-erfurt/Businesshotel-Roommanager#20]
Räume brauchen entweder einen Zeitplan in dem steht wann welcher Raum belegt ist oder ein Attribut was diese Eigenschaften beinhaltet
Zeitplan wäre präferiert

alles absolut notwendig, um BookingRequests autonom zu bearbeiten

**Comment by Thom-Mon** [comment]
Sollte doch genügen über den TimeFrame bzw. den Dateframe oder beides einen Raum überprüfen zu können und danach im Anschluss falls nötig einen Zeitplan zu erstellen

**Comment by nikschen** [comment]
dann kann ein raum aber immer nur einen zeitraum beinhalten, buchungen sind aber fürgewöhnlich, deshalb ein zeitplan als array in dem jeweils ein zeitraum und ein raum gespeichert sind
