### ISSUE TITLE
Datenbankmodellierung II.

### ISSUE THREAD

**Issue by nikschen** [fh-erfurt/Businesshotel-Roommanager#32]
wie im Meeting besprochen, Aufteilung der Tabellen nach Vorbild der Java Klassen

**Comment by Thom-Mon** [comment]
Die ersten Änderungen wurden vorgenommen, Änderungen bzw. Aufteilung der Booking und Rooms steht noch aus. Wir aber spätestens zum nächsten Meeting stehen.
