### ISSUE TITLE
Booking -Aufteilung- in DB sinnvoll?

### ISSUE THREAD

**Issue by Thom-Mon** [fh-erfurt/Businesshotel-Roommanager#35]
Nach Prüfung der beiden Klassen für HotelroomBooking und ConferenceroomBooking stellt sich mir die Frage, ob eine Aufteilung der Tabelle Booking sinnvoll ist. 

Grund für die Zweifel ist, dass @Kalypfenking in #31 eine Anpassung an der Timeframe bzw Dateframe vornimmt und diese vereinheitlicht in der klasse date. 

Die Unterscheidung der Dateframe und der Timeframe ist aber der einzige Unterschied zwischen den beiden Bookings (Hotel/Conference). Selbst die Preisberechnung findet auf ähnlicher Basis statt nur mit dem Unterschied, dass Stunden statt Tage in Konferenzräumen abgerechnet werden.

nach meiner Einschätzung erfolgt die Unterscheidung der Buchung allein durch die Räume in ausreichender Weise.

Hierzu würde ich gerne nochmal mit dem Team diskutieren.

**Comment by nikschen** [comment]
> Nach Prüfung der beiden Klassen für HotelroomBooking und ConferenceroomBooking stellt sich mir die Frage, ob eine Aufteilung der Tabelle Booking sinnvoll ist.
> 
> Grund für die Zweifel ist, dass @Kalypfenking in #31 eine Anpassung an der Timeframe bzw Dateframe vornimmt und diese vereinheitlicht in der klasse date.
> 
> Die Unterscheidung der Dateframe und der Timeframe ist aber der einzige Unterschied zwischen den beiden Bookings (Hotel/Conference). Selbst die Preisberechnung findet auf ähnlicher Basis statt nur mit dem Unterschied, dass Stunden statt Tage in Konferenzräumen abgerechnet werden.
> 
> nach meiner Einschätzung erfolgt die Unterscheidung der Buchung allein durch die Räume in ausreichender Weise.
> 
> Hierzu würde ich gerne nochmal mit dem Team diskutieren.

Würd ich so unterschreiben, da dürfte die Unterscheidung auf Klassenebene, eigentlich ja nur bei der Preisberechnung, ausreichen

**Comment by Thom-Mon** [comment]
Denke auch... die Preisberechnng schaue ich mir dann nochmal gesondert an und würde dann dieses Issue danach direkt wieder schließen.

**Comment by Thom-Mon** [comment]
Erledigt und vom Team abgesegnet...
