### ISSUE TITLE
Erstellen einer grafischen Darstellung für die Präsentation am 16.11.2020

### ISSUE THREAD

**Issue by Thom-Mon** [fh-erfurt/Businesshotel-Roommanager#4]
Erstelle eine nette grafische Darstellung unserer Projektidee. Eventuell ist da nochmal Rücksprache mit dem KalyphenKing notwendig, dass am Ende auch alles stimmig ist. 
MartinJugi haut dann alles zusammen.

**Comment by nikschen** [comment]
@MartinJugi Bitte die Grafik mit in die Powerpoint aufnehmen
