### ISSUE TITLE
Testfälle erstellen in IDE lernen

### ISSUE THREAD

**Issue by Thom-Mon** [fh-erfurt/Businesshotel-Roommanager#5]
### Jeder sollte:
* das Video von Hr. Hecht zum einfachen Test-Driven-Development gesehen haben
 * [Link zum Video](https://www.youtube.com/watch?v=BseU_mYz-LQ&feature=youtu.be)
* Testfälle aus Methoden erstellen können
* Testfälle in Klassen erstellen können
* den Aufbau und Umgang mit JUnit beherrschen/kennen
* Testupload machen und als Commit auf diesen Issue veweisen lassen

**Comment by nikschen** [comment]
@MartinJugi  hier kannst du deine Verknüpfung von IntelliJ und GitHub testen, Referenz auf das Issue nicht vergessen

**Comment by Thom-Mon** [comment]
Alle wissen Bescheid. Nach einem Semester sollte es dazu keinerlei Fragen geben, also zumindest keine die ein Issue erfordern.
