### ISSUE TITLE
Gesamtpreisanzeige bei Konferenzraum funktioniert nicht

### ISSUE THREAD

**Issue by Thom-Mon** [fh-erfurt/Businesshotel-Roommanager#50]
Zeigt immer den Gesamtpreis mit 0 € an.

**Comment by Kalyphenking** [comment]
Ja vergessen zu pushen gestern Abend und hab jetzt wieder Unordnung im Projekt aber ist ansich funktionsfähig

**Comment by Thom-Mon** [comment]
Funktioniert nun einwandfrei
